apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  labels:
    name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 10s

    scrape_configs:
      - job_name: "kubernetes-nodes"
        kubernetes_sd_configs:
          - role: node

      - job_name: "kubernetes-pods"
        kubernetes_sd_configs:
          - role: pod

      - job_name: "go-app"
        static_configs:
          - targets: ["go-app-service.default.svc.cluster.local:80"]
